export const caseStudies = [
  {
    id: 'leibnitz-rasen',
    town: 'Leibnitz',
    service: 'Rasenpflege',
    objectType: 'Privatgarten',
    challenge: 'Unregelmaessiges Wachstum und unsaubere Kanten.',
    approach: 'Fixer 14-Tage-Rhythmus mit Kantenpflege und Laubentfernung.',
    result: 'Gleichmaessiges Gesamtbild waehrend der gesamten Hauptsaison.',
    cadence: '14-taegig',
  },
  {
    id: 'wagna-hecke',
    town: 'Wagna',
    service: 'Heckenpflege',
    objectType: 'Einfamilienhaus',
    challenge: 'Ueberwachsene Hecke an Gehweg und Einfahrt.',
    approach: 'Schonender Formschnitt in zwei Durchgaengen und saubere Entsorgung.',
    result: 'Klare Linien, bessere Sicht und gepflegter Eingangsbereich.',
    cadence: '2x pro Jahr',
  },
  {
    id: 'gralla-objekt',
    town: 'Gralla',
    service: 'Aussenanlagenbetreuung',
    objectType: 'Wohnanlage',
    challenge: 'Schwankende Pflegequalitaet durch wechselnde Anbieter.',
    approach: 'Monatlicher Pflegeplan mit fixer Ansprechpartnerin und Checkliste.',
    result: 'Konstant gepflegte Gruenflaechen und planbare Betreuung.',
    cadence: 'monatlich',
  },
  {
    id: 'tillmitsch-saison',
    town: 'Tillmitsch',
    service: 'Saisonservice',
    objectType: 'Firmenflaeche',
    challenge: 'Hoher Pflegebedarf in Fruehling und Herbst.',
    approach: 'Saisonale Intensivtermine mit Fokus auf Sauberkeit und Sicherheit.',
    result: 'Aussenflaechen wirken ganzjaehrig ordentlich und einladend.',
    cadence: 'saisonal',
  },
]
