export const caseStudies = [
  {
    id: 'leibnitz-rasen',
    town: 'Leibnitz',
    service: 'Rasenpflege',
    objectType: 'Privatgarten',
    challenge: 'Unregelmäßiges Wachstum und unsaubere Kanten.',
    approach: 'Fixer 14-Tage-Rhythmus mit Kantenpflege und Laubentfernung.',
    result: 'Gleichmäßiges Gesamtbild während der gesamten Hauptsaison.',
    cadence: '14-tägig',
  },
  {
    id: 'wagna-hecke',
    town: 'Wagna',
    service: 'Heckenpflege',
    objectType: 'Einfamilienhaus',
    challenge: 'Überwachsene Hecke an Gehweg und Einfahrt.',
    approach: 'Schonender Formschnitt in zwei Durchgängen und saubere Entsorgung.',
    result: 'Klare Linien, bessere Sicht und gepflegter Eingangsbereich.',
    cadence: '2x pro Jahr',
  },
  {
    id: 'gralla-objekt',
    town: 'Gralla',
    service: 'Außenanlagenbetreuung',
    objectType: 'Wohnanlage',
    challenge: 'Schwankende Pflegequalität durch wechselnde Anbieter.',
    approach: 'Monatlicher Pflegeplan mit fixer Ansprechpartnerin und Checkliste.',
    result: 'Konstant gepflegte Grünflächen und planbare Betreuung.',
    cadence: 'monatlich',
  },
  {
    id: 'tillmitsch-saison',
    town: 'Tillmitsch',
    service: 'Saisonservice',
    objectType: 'Firmenfläche',
    challenge: 'Hoher Pflegebedarf in Frühling und Herbst.',
    approach: 'Saisonale Intensivtermine mit Fokus auf Sauberkeit und Sicherheit.',
    result: 'Außenflächen wirken ganzjährig ordentlich und einladend.',
    cadence: 'saisonal',
  },
]
